apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
    - context: packages/react-gatsby
      image: react-gatsby
  tagPolicy:
    sha256: {}
deploy:
  kubectl:
    manifests:
      - k8s/**.yaml
